[package]
authors = ["Michael Lodder <redmike7@gmail.com>", "Dave Huseby <dave@linuxprogrammer.org>"]
categories = ["cryptography", "no-std", "algorithms"]
description = "Verifiable Secret Sharing Schemes for splitting, combining and verifying secret shares"
documentation = "https://docs.rs/vsss-rs"
edition = "2021"
homepage = "https://github.com/mikelodder7/vsss-rs"
keywords = ["crypto", "sharing", "secret", "verifiable"]
license = "Apache-2.0 OR MIT"
name = "vsss-rs"
readme = "README.md"
repository = "https://github.com/mikelodder7/vsss-rs"
version = "2.1.0"

[features]
default = ["secp256k1", "curve25519", "std"]
alloc = ["serde_cbor"]
curve25519 = ["curve25519-dalek", "subtle"]
secp256k1 = ["k256", "elliptic-curve", "subtle"]
std = ["alloc"]

[dependencies]
curve25519-dalek = {git = "https://github.com/tari-project/curve25519-dalek", tag = "v4.0.1", optional = true, default-features = false, features = ["serde", "alloc", "u64_backend"] }
elliptic-curve = { version = "0.12", features = ["ecdh"], optional = true }
ff = "0.12"
group = "0.12"
k256 = { version = "0.11", features = ["arithmetic", "bits", "serde"], optional = true }
rand_chacha = { version = "0.3", default-features = false }
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["serde_derive"] }
serde-big-array = "0.4"
serde_cbor = { version = "0.11", optional = true }
sha2 = { version = "0.10", default-features = false }
sha2v9 = { version = "0.9", package = "sha2", default-features = false }
subtle = { version = "2.4", optional = true }
zeroize = { version = "1", features = ["zeroize_derive"] }
rand_7 = { version = "0.7", package = "rand" }
sha3 = { version = "0.9.1", default-features = false }

[dev-dependencies]
bls12_381_plus = "0.5.3"
curve25519-dalek = {git = "https://github.com/tari-project/curve25519-dalek", tag = "v4.0.1", default-features = false, features = ["serde", "alloc", "u64_backend"] }
ed25519-dalek = "1.0"
k256 = { version = "0.11.6", features = ["arithmetic", "bits"] }
p256 = { version = "0.11.1", features = ["arithmetic", "bits"] }
rand = "0.8"
rand_7 = { version = "0.7", package = "rand" }
rand_xorshift = "0.3"
serde_json = "1.0"
serde_cbor = "0.11"
serde_bare = "0.5"
sha2v9 = { version = "0.9", package = "sha2" }
x25519-dalek = "1.1"
