# Runs daily at 12:10
name: Security audit
on:
  schedule:
    - cron:  '10 12 * * *'
jobs:
  security_audit:
    runs-on: [self-hosted, linux] 
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
